substitutions:
  esp_name: Bettbelegung Schlafzimmer #Device Name
  esp_hostname: bettbelegung_schlafzimmer
  run_time: 24h #can be as long as needed to get data 
  sleep_time: 1min # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.11.30.120

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

time: !include common/time.yaml

sun: !include common/sun.yaml 

mqtt: !include common/mqtt.yaml

deep_sleep:
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
  
text_sensor:
  - <<: !include common/text_sensor_sunrise.yaml
  - <<: !include common/text_sensor_sunset.yaml
  - <<: !include common/text_wifiinfo.yaml
  
sensor:
  - <<: !include common/sensor_wifisignal.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Belegung1"
    device_class: presence

  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Belegung2"
    device_class: presence
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Belegung3"
    device_class: presence
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Belegung4"
    device_class: presence
output:
  - platform: gpio
    pin: GPIO16
    id: gpio_16