substitutions:
  esp_name: Bodenfeuchte_1 #Device Name
  esp_hostname: bodenfeuchte1
  
esphome:
  name: ${esp_hostname}

  platform: ESP32
  board: lolin_d32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.11.31.159
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password
    

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

sun: !include common/sun.yaml 

mqtt: !include common/mqtt.yaml

esp32_ble_tracker:
binary_sensor:
  - platform: ble_presence
    mac_address: !secret g6_mac
    name: "DexCom MAC at CO2 detected"

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - hours: 21,22,23,0,1,2,3,4,5
        then:
        - lambda: |-
            id(deep_sleep_1).set_sleep_duration(60*60000);
            id(deep_sleep_1).setup();
      - hours: 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
        then:
        - lambda: |-
            id(deep_sleep_1).set_sleep_duration(10*60000);
            id(deep_sleep_1).setup();

deep_sleep:
  run_duration: 60s
  sleep_duration: 10s
  id: deep_sleep_1


sensor:
  - <<: !include common/sensor_wifisignal.yaml
  - platform: adc
    pin: 32
    name: "${esp_hostname}_1"
    update_interval: 120s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - lambda: |-
        if (x > 3.3) {
            return 0;
          } else if (x < 1.10) {
            return 100;
          } else {
            return (3.3-x) / (3.3-1.10) * 100.0;
          }
  - platform: adc
    pin: 33
    name: "${esp_hostname}_2"
    update_interval: 120s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - lambda: |-
        if (x > 3.3) {
            return 0;
          } else if (x < 1.10) {
            return 100;
          } else {
            return (3.3-x) / (3.3-1.10) * 100.0;
          }
  - platform: adc
    pin: 34
    name: "${esp_hostname}_3"
    update_interval: 120s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - lambda: |-
        if (x > 3.3) {
            return 0;
          } else if (x < 1.10) {
            return 100;
          } else {
            return (3.3-x) / (3.3-1.10) * 100.0;
          }
  - platform: adc
    pin: 35
    name: "${esp_hostname}_4"
    update_interval: 120s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - lambda: |-
        if (x > 3.3) {
            return 0;
          } else if (x < 1.10) {
            return 100;
          } else {
            return (3.3-x) / (3.3-1.10) * 100.0;
          }