substitutions:
  esp_name: dstike #Device Name
  esp_hostname: dstike
  sleep_time: 5min # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.11.30.116
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

#time: !include common/time.yaml

#sun: !include common/sun.yaml 

#mqtt: !include common/mqtt.yaml

#deep_sleep:
#  sleep_duration: ${sleep_time}
#  run_duration: 60min
#  id: deep_sleep_1

text_sensor:
#  - <<: !include common/text_sensor_sunrise.yaml
#  - <<: !include common/text_sensor_sunset.yaml
  - platform: homeassistant
    entity_id: sensor.flsunq5_time_remaining
    id: flsunq5_time_remaining
  - platform: homeassistant
    entity_id: sensor.ender5_time_remaining
    id: ender5_time_remaining

font: !include common/fonts.yaml

binary_sensor:
  - platform: homeassistant
    entity_id: switch.tasmota_e868e7469f95_switch_relay_1
    id: flsunq5_switch
    #on_state:
    #  - display.page.show: !lambda |-
    #       if (id(flsunq5_switch).state) {
    #         return id(page1);
    #       } else {
    #         return id(page3);
    #       }
sensor:
  - <<: !include common/sensor_wifisignal.yaml
  - platform: uptime
    name: "${esp_name}Uptime Sensor"
    id: uptime_sensor
    update_interval: 10s
    #on_value_range:
    #  - above: 60
    #    then:
    #    - display.page.show: page3
  - platform: homeassistant
    entity_id: sensor.ender5_hotend_actual
    id: ender5_hotend_actual
    on_value_range:
      - above: 50
        then:
        - display.page.show: page2
      - below: 50
        then:
        - display.page.show: page1
  - platform: homeassistant
    entity_id:  sensor.ender5_current_progress
    id: ender5_current_progress
  - platform: homeassistant
    entity_id: sensor.flsunq5_hotend_actual
    id: flsunq5_hotend_actual
    #on_value_range:
    #  - above: 50
    #    then:
    #    - display.page.show: page2
    #  - below: 50
    #    then:
    #    - display.page.show: page1
  - platform: homeassistant
    entity_id: sensor.flsunq5_current_progress
    id: flsunq5_current_progress
  - platform: homeassistant
    entity_id: sensor.humidity_158d0002c8e3d8
    id: sensor_aktive_box
  - platform: homeassistant
    entity_id: sensor.humidity_158d0002c7737f
    id: sensor_lagerbox
  - platform: homeassistant
    entity_id: sensor.flsunq5_bed_actual
    id: flsunq5_bed_actual
  - platform: homeassistant
    entity_id: sensor.ender5_bed_actual
    id: ender5_bed_actual
  - platform: homeassistant
    entity_id: sensor.lumi_lumi_sens_temperature
    id: petg_aktive_box_temperature
  - platform: homeassistant
    entity_id: sensor.lumi_lumi_sens_humidity
    id: petg_aktive_box_humidity
  - platform: homeassistant
    entity_id: sensor.lumi_lumi_weather_194ca006_humidity
    id: petg_passive_box_humidity
  - platform: homeassistant
    entity_id: sensor.lumi_lumi_weather_194ca006_temperature
    id: petg_passive_box_temperature
  - platform: homeassistant
    entity_id: sensor.hx711_links
    id: filamentrolle_links
  - platform: homeassistant
    entity_id: sensor.hx711_rechts
    id: filamentrolle_rechts
    
i2c:
  sda: 5
  scl: 4

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: 16
    address: 0x3C
    update_interval: 5s
    contrast: 60%
    rotation: 0°
    pages:
      - id: page1
        lambda: |-
          it.printf(0, 0, id(sans_medium_15), TextAlign::TOP_LEFT, "R1: %.0fg", id(filamentrolle_links).state);
          it.printf(128, 0, id(sans_medium_15), TextAlign::TOP_RIGHT, "R2:%.0fg", id(filamentrolle_rechts).state);
          it.printf(0, 15, id(sans_medium_15), TextAlign::TOP_LEFT, "aktiv:%.0f%%", id(petg_aktive_box_temperature).state);
          it.printf(0, 30, id(sans_medium_15), TextAlign::TOP_LEFT, "pass.: %.0f%%", id(petg_passive_box_humidity).state);
          it.printf(0, 45, id(sans_medium_15), TextAlign::TOP_LEFT, "E5:%.0f°C, Q5:%.0f°C", id(ender5_bed_actual).state, id(flsunq5_bed_actual).state);
      - id: page2
        lambda: |-
          it.printf(0, 0, id(sans_medium_10), "E5: %.0f%%, H: %.0f°C, B:%.0f°C", id(ender5_current_progress).state, id(ender5_hotend_actual).state, id(ender5_bed_actual).state);
          it.printf(0, 15, id(sans_medium_10), "Zeit: %s, R1: %.0f%g", id(ender5_time_remaining).state.c_str(),id(filamentrolle_links).state);
          it.printf(0, 30, id(sans_medium_10), "Q5: %.0f%%, H: %.0f°C, B: %.0f°C", id(flsunq5_current_progress).state, id(flsunq5_hotend_actual).state, id(flsunq5_bed_actual).state);
          it.printf(0, 45, id(sans_medium_10), "Zeit: %s, R2: %.0f%%", id(flsunq5_time_remaining).state.c_str(), id(filamentrolle_rechts).state);
          it.printf(0, 60, id(sans_medium_10), "A-Box: %.0f%%, Lagerbox: %.0f%%", id(sensor_aktive_box).state, id(sensor_lagerbox).state);
      - id: page3
        lambda: |-
#      it.strftime(0, 45, id(font_cs_10), "%H:%M:%S", id(flsunq5_time_remaining).state);
#      it.printf(0, 45, id(font_cs_10), "Remaining: %s", id(flsunq5_time_remaining).state.c_str());
#      it.printf(80,0, id(font_cs_10), "Temp: %.1f°C", id(ender3pro_hotend_actual).state);
#      it.print(0, 20, id(font_cs_10), "Q5:");
#//      it.strftime(60, 20, id(font_cs_10), "%H:%M", id(flsunq5_time_remaining).state);
