substitutions:
  esp_name: esp-neuendorf1-dallas-ds18b20 #Device Name
  esp_hostname: esp-neuendorf1-dallas-ds18b20
  run_time: 24h #can be as long as needed to get data 
  sleep_time: 10sec # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: wemos_d1_mini32
  
wifi:
  ssid: !secret wifi_ssid_neuendorf
  password: !secret wifi_password_neuendorf
  #use_address: 10.11.30.111

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

time: !include common/time.yaml

sun: !include common/sun.yaml 

#mqtt: !include common/mqtt.yaml

deep_sleep:
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
  
text_sensor:
  - <<: !include common/text_sensor_sunrise.yaml
  - <<: !include common/text_sensor_sunset.yaml

sensor:
  - <<: !include common/sensor_wifisignal.yaml
  - platform: dallas
    address: 0xc13c01e076898628
    name: "Temperatur Sauna"
    
dallas:
  - pin: 23