substitutions:
  # Set the MAC address of your device here
  mac_address: !secret dexcom_mac
  transmitter_id: !secret dexcom_transmitter_id
  use_alternative_bt_channel: "false"
  esp_name: esp-test #Device Name
  esp_hostname: esp-test
  run_time: 999h #can be as long as needed to get data 
  sleep_time: 1min # normal sleep time

esphome:
  name: ${esp_hostname}

#external_components:
#  - source: github://pr#4256
#    components: [ wireguard ]
#wireguard:
#  address: 10.0.50.20
#  private_key: !secret wireguard_key_esp_test
#  peer_key: E3X5676O4u08VaFOvL+H3EGVvbfPVXqoDyrDIahw+CE=
#  peer_endpoint: frontend.schmidtie.net
#  peer_port: 23456

external_components:
  - source: github://Fabian-Schmidt/esphome-dexcom
    refresh: always

esp32:
  board: wemos_d1_mini32

logger:
  # baud_rate: 2000000
  level: VERBOSE
  # level: DEBUG

esp32_ble:

ble_client:
  - mac_address: ${mac_address}
    id: dexcom_ble_client_id

sensor:
  - platform: dexcom
    ble_client_id: dexcom_ble_client_id
    transmitter_id: ${transmitter_id}
    use_alternative_bt_channel: ${use_alternative_bt_channel}
    glucose_in_mg_dl:
      name: Glucose in mg/dl
    glucose_in_mmol_l:
      name: Glucose in mmol/l

wifi:
  use_address: 10.11.30.123
  networks:
  - ssid: eduroam
    eap:
      identity: !secret eduroam_user
      username: !secret eduroam_user
      password: !secret eduroam_password    
      certificate_authority: ca_cert.pem
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  #ssid: eduroam
  #use_address: 10.0.50.20
  #eap:
  #    identity: !secret eduroam_user
  #    username: !secret eduroam_user
  #    password: !secret eduroam_password    
  #    certificate_authority: ca_cert.pem
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

mqtt: !include common/mqtt.yaml

time:
  - platform: sntp

deep_sleep:
  run_duration: ${run_time}
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
