substitutions:
  esp_name: esp-neuendorf3-co2 #Device Name
  esp_hostname: esp-neuendorf3-co2
  run_time: 24h #can be as long as needed to get data 
  sleep_time: 10sec # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP8266
  board: d1_mini

wifi:

  networks:
   - ssid: !secret wifi_ssid_neuendorf
     password: !secret wifi_password_neuendorf
   - ssid: !secret wifi_ssid
     password: !secret wifi_password
  use_address: 10.11.30.167

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

time: !include common/time.yaml

sun: !include common/sun.yaml 

mqtt: !include common/mqtt.yaml

deep_sleep:
  run_duration: ${run_time}
  sleep_duration: ${sleep_time}
  id: deep_sleep_1

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a
  
text_sensor:
  - <<: !include common/text_sensor_sunrise.yaml
  - <<: !include common/text_sensor_sunset.yaml

uart:   
  - id: co2
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
  
sensor:
  - <<: !include common/sensor_wifisignal.yaml
  - platform: mhz19
    uart_id: co2
    co2:
      name: ${esp_hostname} CO2 Value
      internal: false
    temperature:
      name: ${esp_hostname} CO2 Sensor Temperature
      internal: false
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: sht3xd
    i2c_id: bus_a
    temperature:
      name: ${esp_hostname} Temperature
      internal: false
    humidity:
      name: ${esp_hostname} Humidity
      internal: false
    address: 0x44
    update_interval: 10s