substitutions:
  esp_name: esp-test #Device Name
  esp_hostname: esp-test
  run_time: 999h #can be as long as needed to get data 
  sleep_time: 1min # normal sleep time
  
#esp8266:
#  board: esp01_1m
esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: wemos_d1_mini32

external_components:
  - source: github://pr#4256
    components: [ wireguard ]
wireguard:
  address: 10.0.50.20
  private_key: !secret wireguard_key_esp_test
  peer_key: E3X5676O4u08VaFOvL+H3EGVvbfPVXqoDyrDIahw+CE=
  peer_endpoint: frontend.schmidtie.net
  peer_port: 23456

wifi:
  ssid: eduroam
  use_address: 10.0.50.20
  eap:
      identity: !secret eduroam_user
      username: !secret eduroam_user
      password: !secret eduroam_password    
      certificate_authority: ca_cert.pem
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  #use_address: 10.11.30.111

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

#mqtt: !include common/mqtt.yaml

time:
  - platform: sntp

deep_sleep:
  run_duration: ${run_time}
  sleep_duration: ${sleep_time}
  id: deep_sleep_1

switch:
  - platform: restart
    name: "Sonoff S20 Restart"

dallas:
  - pin: 23