substitutions:
  esp_name: esp-test #Device Name
  esp_hostname: esp-test
  run_time: 999h #can be as long as needed to get data 
  sleep_time: 1min # normal sleep time
  
esphome:
  name: ${esp_hostname}

esp8266:
  board: esp01_1m

wifi:
  use_address: 10.11.30.216
  networks:
  - ssid: meraki-eduroam
    eap:
      identity: "ms1511@uni-rostock.de"
      username: "ms1511@uni-rostock.de"
      password: "E3afo582!neu"
      certificate_authority: ca_cert.pem
  - ssid: !secret wifi_ssid
    password: !secret wifi_password


logger:

api:
  password: !secret password

ota:
  password: !secret password

mqtt: !include common/mqtt.yaml

deep_sleep:
  run_duration: ${run_time}
  sleep_duration: ${sleep_time}
  id: deep_sleep_1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff S20 Button"
  - platform: status
    name: "Sonoff S20 Status"
  - platform: gpio
    pin: GPIO2
    name: "Sonoff S20 Sensor"

switch:
  - platform: restart
    name: "Sonoff S20 Restart"

output:
  - platform: esp8266_pwm
    id: s20_green_led
    pin:
      number: GPIO13
      inverted: true
  # Note: do *not* make the relay a dimmable (PWM) signal, relays cannot handle that
  - platform: gpio
    id: s20_relay
    pin: GPIO12

light:
  - platform: monochromatic
    name: "Sonoff S20 Green LED"
    output: s20_green_led
  - platform: binary
    name: "Sonoff S20 Relay"
    output: s20_relay