substitutions:
  esp_name: HX711-2 #Device Name
  esp_hostname: hx711-2
  run_time: 10h #can be as long as needed to get data 
  sleep_time: 5min # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.11.30.178

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret password

time: !include common/time.yaml

sun: !include common/sun.yaml 

mqtt: !include common/mqtt.yaml

deep_sleep:
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
  
text_sensor:
  - <<: !include common/text_sensor_sunrise.yaml
  - <<: !include common/text_sensor_sunset.yaml
  - <<: !include common/text_wifiinfo.yaml
  
sensor:
  - <<: !include common/sensor_wifisignal.yaml

  - platform: hx711
    name: "HX711_2_1"
    dout_pin: 'D4'
    clk_pin: 'D3'
    gain: 128
    update_interval: 10s
    filters:
      - filter_out: 0
      - max:
          window_size: 7
          send_every: 3
          send_first_at: 2
      #- multiply: -1
      - calibrate_linear:
          - 104611 -> 0
          - 537083 -> 1185
    unit_of_measurement: g
    internal: false
    
  - platform: hx711
    name: "HX711_2_2"
    dout_pin: 'D2'
    clk_pin: 'D1'
    gain: 128
    update_interval: 10s
    filters:
      - filter_out: 0
      - max:
          window_size: 7
          send_every: 3
          send_first_at: 2
      #- multiply: -1
      - calibrate_linear:
          - -182428 -> 0
          - -249871 -> 171
          - -499868 -> 795
    unit_of_measurement: g
    internal: false