substitutions:
  esp_name: HX711 #Device Name
  esp_hostname: hx711
  run_time: 10h #can be as long as needed to get data 
  sleep_time: 5min # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: wemos_d1_mini32
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: 10.11.30.111

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

time: !include common/time.yaml

sun: !include common/sun.yaml 

mqtt: !include common/mqtt.yaml

deep_sleep:
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
  
text_sensor:
  - <<: !include common/text_sensor_sunrise.yaml
  - <<: !include common/text_sensor_sunset.yaml

sensor:
  - <<: !include common/sensor_wifisignal.yaml

  - platform: hx711
    name: "HX711 links"
    dout_pin: '16'
    clk_pin: '17'
    gain: 128
    update_interval: 60s
    filters:
      ##- multiply: -1
      - calibrate_linear:
          - -361004 -> 0
          - -428839 -> 171
          - -674148 -> 795
    unit_of_measurement: g
    internal: false
    
  - platform: hx711
    name: "HX711 rechts"
    dout_pin: '21'
    clk_pin: '22'
    gain: 128
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 182428 -> 0
          - 249871 -> 171
          - 499868 -> 795
    unit_of_measurement: g
    internal: false