substitutions:
  esp_name: HX711 #Device Name
  esp_hostname: hx711
  run_time: 10h #can be as long as needed to get data 
  sleep_time: 5min # normal sleep time
  
esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: wemos_d1_mini32
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.11.30.137

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

time: !include common/time.yaml

sun: !include common/sun.yaml 

mqtt: !include common/mqtt.yaml

deep_sleep:
  sleep_duration: ${sleep_time}
  id: deep_sleep_1
  
text_sensor:
  - <<: !include common/text_sensor_sunrise.yaml
  - <<: !include common/text_sensor_sunset.yaml

sensor:
  - <<: !include common/sensor_wifisignal.yaml

  - platform: hx711
    name: "HX711 Value"
    dout_pin: '26'
    clk_pin: '18'
    gain: 128
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 46350 -> 0
          - 75358 ->0.074
          - 590000 -> 1.400
    unit_of_measurement: kg