substitutions:

###### CHANGE ME START ######

  device_name: "nspanelwohnzimmer" 
  wifi_ssid:  !secret wifi_ssid
  #wifi_ssid: "www.schmidtie.net"
  wifi_password: !secret wifi_password
  #use_address: 10.11.35.149
  use_address: 10.11.30.125
  ota_password: !secret wifi_hotspot_password

  nextion_update_url: "http://ha.imme40.schmidtie.net:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  #localpack: !include nspanel_esphome_local.yaml
  remote_package:
    #url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    url: https://github.com/tremor/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####