substitutions:
  esp_name: TTGO T4 Display #Device Name
  esp_hostname: ttgo-t4
  
esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: nodemcu-32s
  on_boot:
    then:
    - wait_until:
       api.connected:
    - lambda: |-
          id(markerpoint).publish_state(0);

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.11.30.75


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_hostname}"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

globals:
  - id: mark
    type: int
    restore_value: no
    initial_value: '0' 
color:
  - id: RED
    red: 100%
    green: 0%
    blue: 0%
  - id: YELLOW
    red: 100%
    green: 100%
    blue: 0%
  - id: GREEN
    red: 0%
    green: 100%
    blue: 0%
  - id: BLUE
    red: 0%
    green: 0%
    blue: 100%
    white: 1.0000
  - id: GRAY
    red: 50%
    green: 50%
    blue: 50%
  - id: WHITE
    red:   1.0000
    green: 1.0000
    blue:  1.0000
    white: 0.0000
  - id: BLACK
    red: 0%
    green: 0%
    blue: 0%
 
font:
  - file: "fonts/GoogleSans-Bold.ttf"
    id: sans_bold_38
    size: 38
  - file: "fonts/GoogleSans-Medium.ttf"
    id: sans_medium_56
    size: 56    
  - file: "fonts/GoogleSans-Medium.ttf"
    id: sans_medium_28
    size: 28
  - file: "fonts/GoogleSans-Medium.ttf"
    id: sans_medium_20
    size: 20
  - file: "fonts/GoogleSans-Medium.ttf"
    id: sans_medium_14
    size: 14
  - file: "fonts/GoogleSans-Medium.ttf"
    id: sans_medium_10
    size: 10
time:
  - platform: homeassistant
    id: ntp
    timezone: Europe/Berlin
    
sensor:
  - platform: template
    id: markerpoint
    on_value_range:
      - above: 11
        then:
         - lambda: |-
            id(markerpoint).state = 0;
      - below: 0
        then:
        - lambda: |-
              id(markerpoint).state = 11;
  - platform: wifi_signal
    name: "WiFi Signal Sensor TTGO Display"
    update_interval: 60s
  - platform: homeassistant
    entity_id: sensor.blood_sugar_mmol
    id: blood_sugar_mmol
    internal: true
  - platform: homeassistant
    entity_id: sensor.temperatur_und_luftfeuchtigkeitssensor_temperature
    id: schlafzimmer_temp
    internal: true
  - platform: homeassistant
    entity_id: sensor.temperatur_und_luftfeuchtigkeitssensor_humidity
    id: schlafzimmer_humid
    internal: true
  - platform: homeassistant
    entity_id: sensor.bh1750_illuminance_2
    id: schlafzimmer_illumination
    internal: true
  - platform: homeassistant
    entity_id: sensor.mh_z19_co2_value_2
    id: schlafzimmer_co2
    internal: true

  - platform: homeassistant
    entity_id: sensor.temperatur_und_luftfeuchtigkeitssensor_mit_display_humidity
    id: wohnzimmer_humid
    internal: true
  - platform: homeassistant
    entity_id: sensor.temperatur_und_luftfeuchtigkeitssensor_mit_display_temperature
    id: wohnzimmer_temp
    internal: true
  - platform: homeassistant
    entity_id: sensor.xiaomi_lumi_sen_ill_mgl01_illuminance
    id: wohnzimmer_illumination
    internal: true


    
  - platform: homeassistant
    entity_id: sensor.tempf_lacrosse204_temperature
    id: dachboden_temp
    internal: true
  - platform: homeassistant
    entity_id: sensor.tempf_lacrosse204_humidity
    id: dachboden_humid
    internal: true
  - platform: homeassistant
    entity_id: sensor.xiaomi_lumi_sen_ill_mgl01_3d351a00_illuminance
    id: dachboden_illumination
    internal: true

script:
  - id: check_markerpoint_below
    then:
      - if:
         condition:
           lambda: 'return id(markerpoint).state == -1;'
         then:
           - lambda: |-
              id(markerpoint).state = 11;
           - logger.log: "Below 0"
  - id: check_markerpoint_above
    then:
      - if:
         condition:
           lambda: 'return id(markerpoint).state == 12;'
         then:
           - lambda: |-
              id(markerpoint).state = 0;
           - logger.log: "Above 11"
           
  - id: button_toggle
    then:
           lambda: |-
                  if ((id(markerpoint).state == 0)) {
                    id(switch_0).toggle();
                  }
                  else if ((id(markerpoint).state == 1)) {
                    id(switch_1).toggle();
                  }
                  else if ((id(markerpoint).state == 2)) {
                    id(switch_2).toggle();
                  }
                  else if ((id(markerpoint).state == 3)) {
                    id(switch_3).toggle();
                  }
                  else if ((id(markerpoint).state == 4)) {
                    id(switch_4).toggle();
                  }
                  else if ((id(markerpoint).state == 5)) {
                    id(switch_5).toggle();
                  }
                  else if ((id(markerpoint).state == 6)) {
                    id(switch_6).toggle();
                  }
                  else if ((id(markerpoint).state == 7)) {
                    id(switch_7).toggle();
                  }
                  else if ((id(markerpoint).state == 8)) {
                    id(switch_8).toggle();
                  }
                  else if ((id(markerpoint).state == 9)) {
                    id(switch_9).toggle();
                  }
                  else if ((id(markerpoint).state == 10)) {
                    id(switch_10).toggle();
                  }
                  else if ((id(markerpoint).state == 11)) {
                    id(switch_11).toggle();
                  }

binary_sensor:
  - platform: gpio
    name: "BUTTON_LINKS"
    pin:
      number: 39
      inverted: true
    on_press:
      then:
        - lambda: |-
              id(markerpoint).state += 1; 
        - script.execute: check_markerpoint_above
        - switch.turn_on: background
        - display.page.show: wohnzimmer
        - logger.log:       
            format: "Button Down %.0f"
            args: [ 'id(markerpoint).state' ]
        
  - platform: gpio
    name: "BUTTON_RECHTS"
    pin:
      number: 38
      inverted: true
    on_press:
      then:
        - lambda: |-
              id(markerpoint).state -= 1;
        - script.execute: check_markerpoint_below
        - switch.turn_on: background
        - display.page.show: wohnzimmer
        - logger.log:       
            format: "Button Up %.0f"
            args: [ 'id(markerpoint).state' ]
  - platform: gpio
    name: "BUTTON_MITTE"
    pin:
      number: 37
      inverted: true
    on_press:
      then:
        - script.execute: button_toggle
        - display.page.show: wohnzimmer

  - platform: homeassistant
    entity_id: binary_sensor.fenster_wohnzimmer
    id: wohnzimmer_fenster
    internal: true
  - platform: homeassistant
    entity_id: switch.kasa_schalter_1
    id: schlafzimmer_sensor_0
    internal: true
  - platform: homeassistant
    entity_id: switch.lowboard_on_off
    id: wohnzimmer_PS4
    internal: true
  - platform: homeassistant
    entity_id: switch.tz3000_1obwwnmq_ts011f_99ad90fe_on_off_2
    id: wohnzimmer_LowBoard_Fernseher
    internal: true
  - platform: homeassistant
    entity_id: light.wohnzimmer_regal
    id: wohnzimmer_Licht_Regal
    internal: true
  - platform: homeassistant
    entity_id: humidifier.wohnzimmer_befeuchter
    id: wohnzimmer_Befeuchter
    internal: true
  - platform: homeassistant
    entity_id: switch.tz3000_1obwwnmq_ts011f_99ad90fe_on_off_3
    id: wohnzimmer_fujitsu
    internal: true
  - platform: homeassistant
    entity_id: switch.adguard_filtering
    id: sensor_adguard_filtering
    internal: true
  - platform: homeassistant
    entity_id: switch.esstisch_on_off
    id: esstisch_switch_1
    internal: true    
  - platform: homeassistant
    entity_id: switch.tz3000_1obwwnmq_ts011f_7a9747fe_on_off_2
    id: esstisch_switch_2
    internal: true    
  - platform: homeassistant
    entity_id: switch.tz3000_1obwwnmq_ts011f_7a9747fe_on_off_3
    id: esstisch_switch_3
    internal: true    
  - platform: homeassistant
    entity_id: switch.tasmota2_3
    id: wintergarten
    internal: true    
  - platform: homeassistant
    entity_id: switch.sonoff11_th10_bachlauf
    id: bachlauf
    internal: true 
  - platform: homeassistant
    entity_id: switch.tasmota_2
    id: zotac_hdds
    internal: true    

switch:
  - platform: gpio
    pin: 4
    id: background
  - platform: template
    internal: true
    id: switch_0
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_0
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_0
  - platform: template
    internal: true
    id: switch_1
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_1
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_1
  - platform: template
    internal: true
    id: switch_2
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_2
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_2
  - platform: template
    internal: true
    id: switch_3
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_3
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_3
  - platform: template
    internal: true
    id: switch_4
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_4
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_4
  - platform: template
    internal: true
    id: switch_5
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_5
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_5
  - platform: template
    internal: true
    id: switch_6
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_6
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_6
  - platform: template
    internal: true
    id: switch_7
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_7
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_7
  - platform: template
    internal: true
    id: switch_8
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_8
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_8
  - platform: template
    internal: true
    id: switch_9
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_9
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_9
  - platform: template
    internal: true
    id: switch_10
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_10
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_10
  - platform: template
    internal: true
    id: switch_11
    turn_on_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_11
    turn_off_action:
        - wait_until:
            api.connected:
        - homeassistant.event:
           event: esphome.switch_11
           
graph:
  # Show bare-minimum auto-ranged graph
  - id: blood_sugar_mmol_graph
    sensor: blood_sugar_mmol
    duration: 2h
    width: 240
    height: 60
    max_value: 15
    min_value: 2
    x_grid: 30min
spi:
  clk_pin: 18
  miso_pin: 12
  mosi_pin: 23


display:
  - platform: ili9341
    model: TFT_2.4
    cs_pin: 27
    dc_pin: 32
    led_pin: 4
    reset_pin: 5
    rotation: 0
    id: my_display
    update_interval: 500ms
    #auto_clear_enabled: false
    pages:
     - id: wohnzimmer
       lambda: |-
          #define xres 240
          #define yres 320        
          #define firstline 15
          #define nextline 25
          #define seperator 90
          int y = 1;
          it.rectangle(1, (id(markerpoint).state*nextline)+firstline, xres-1, nextline);
          it.print(xres/2, y, id(sans_medium_10), TextAlign::TOP_CENTER, "Wohnzimmer");
          y+=firstline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Regal");
          if (id(wohnzimmer_Licht_Regal).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Lowboard Gaming");
          if (id(wohnzimmer_fujitsu).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Fernseher");
          if (id(wohnzimmer_LowBoard_Fernseher).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Esstisch USB");
          if (id(esstisch_switch_1).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Esstisch 2");
          if (id(esstisch_switch_2).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Esstisch 3");
          if (id(esstisch_switch_3).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Wintergarten");
          if (id(wintergarten).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Bachlauf");
          if (id(bachlauf).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "PS4/Stereo");
          if (id(wohnzimmer_PS4).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "AdGuard");
          if (id(sensor_adguard_filtering).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Festplatten");
          if (id(zotac_hdds).state) {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "An");
          }
          else {
           it.printf(xres, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "Aus");
          }
          y+=nextline;
          
     - id: schlafzimmer
       lambda: |-
          int y = 1;
          it.print(xres/2, y, id(sans_medium_10), TextAlign::TOP_CENTER, "Schlafzimmer");
          y+=firstline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Temperatur");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.1f °C", id(schlafzimmer_temp).state);
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Luftfeuchte");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.0f%%", id(schlafzimmer_humid).state);
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Helligkeit");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.0f lx", id(schlafzimmer_illumination).state);
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "CO2");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.0f mmol", id(schlafzimmer_co2).state);
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Blutzucker");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.1f mmol", id(blood_sugar_mmol).state);
          
          
     - id: dachboden
       lambda: |-
          int y = 1;
          it.print(xres/2, y, id(sans_medium_10), TextAlign::TOP_CENTER, "Dachboden");
          y+=firstline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Temperatur");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.1f °C", id(dachboden_temp).state);
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Luftfeuchte");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.0f%%", id(dachboden_humid).state);
          y+=nextline;
          it.print(1, y, id(sans_medium_20), TextAlign::TOP_LEFT, "Helligkeit");
          it.printf(xres-1, y, id(sans_medium_20), TextAlign::TOP_RIGHT, "%.0f lx", id(dachboden_illumination).state);    